### PR TITLE
Fix for channel-wise simulations

### PR DESCRIPTION
**Pull request by gipert**
Fixes for #5. Not ready to merge, must fix number of events for `nplus_chanwise` and `pplus_chanwise` simulations

### CODE REVIEW

**Comment by gipert** [comment]
Number of primaries should be fixed now, I'll start the corresponding simulations. @vonsturm could you work on `lar_pplus`? Do we want to put all the volumes together in a single simulation?

**Comment by vonsturm** [comment]
Yes but that will have to wait a few days... 
@pandola Question: Do you know how I can merge several cylindrical volumes in the LAr? I would like to simulate in LAr close to p+ for BEGe and for Coax detectors. I don't know if that is possible with macro commands though.

**Comment by pandola** [comment]
@vonsturm I think I have not understood your question. Do you want to generate primaries uniformly sampled from a combination of cylindrical shells?

**Comment by vonsturm** [comment]
Yes I want to sample uniformly from a combination of cylindrical volumes
for complicated reasons :D


On Feb 18, 2018 4:15 PM, "Luciano Pandola" <notifications@github.com> wrote:

@vonsturm <https://github.com/vonsturm> I think I have not understood your
question. Do you want to generate primaries uniformly sampled from a
combination of cylindrical shells?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mppmu/gerda-mage-sim/pull/12#issuecomment-366522973>,
or mute the thread

**Comment by pandola** [comment]
@vonsturm This is possible (by macro, I mean) only if your volumes are physical volumes (i.e. using the volumelist option). If they are geometrical volumes, the macro command is not available and you have to work out the code...

**Comment by gipert** [comment]
@BirgitSchneider conflicts between your macros and changes in this branch should be sort of fixed now, I already relaunched simulations where needed. Could you do a quick check at MPIK (gerda-mage-sim is already checked out in this branch)? See especially how I integrated your additions in `nplus_chanwise`, `nplus_bege` and `nplus_coax`, I used the `UTILS/create-macros/create-oncontacts-chanwise-macros.jl` script. Macros in `lar_pplus` are still wrong, but that will be fixed by @vonsturm in the next days.

**Comment by gipert** [comment]
mmmmh actually not, I simply joined them into vertex files for all BEGes and all Coaxials...

**Comment by BirgitSchneider** [comment]
But we had 1e6 primaries per channel before (still in the master branch) and now 2860829 primaries for the channelwise simulations. Am I missing something here?

**Comment by gipert** [comment]
You mean the macros *using* the vertex files, so yes, I increased statistics in them, but the vertex files are unchanged! I just set up things to use all the available vertices.

**Comment by BirgitSchneider** [comment]
Ah I see. Thanks.

**Comment by gipert** [comment]
Everything seems to work, I'll proceed with merging. There will be a dedicated PR from @vonsturm with new `lar_pplus` simulations.

**Pull request merged**
