### PR TITLE
New (ZAC) resolution curves for pdf-production

### PR DESCRIPTION
**Pull request by gipert**
Implementation of #11. Resolution curves provided by @cransom12 (*to be updated in the future*) and converted in JSON format with `UTILS/post/res-curves-jsonizer.cxx`.

### CODE REVIEW

**Comment by cransom12** [comment]
Hi, I want to check these are the right curves, but I have meetings until 3pm. I will check directly after.

**Comment by gipert** [comment]
That would be great! Thanks

**Comment by cransom12** [comment]
Sorry for the delay! The curves look fine. When I have the new curves available I'll let you know. I should also let you know that possibly the functional form will change to coincide with the supercalibration, but it shouldn't change too much, I think.

**Comment by gipert** [comment]
Fine then, thanks so much for your review!

**Pull request merged**
