### PR TITLE
fixed a typo and added missing macros

### PR DESCRIPTION
**Pull request by BirgitSchneider**
Just fixed a small typo in lar/sur_array/README.md

### CODE REVIEW

**Comment by gipert** [comment]
Thanks, can I merge this?

**Comment by BirgitSchneider** [comment]
I fixed the merge conflict which appeared some hours after the pull request. Should be able to merge again now.

**Comment by gipert** [comment]
Thanks, are you done with commits?

**Comment by BirgitSchneider** [comment]
For now, yes :D

**Pull request merged**
