### PR TITLE
Coin dd

### PR DESCRIPTION
**Pull request by BirgitSchneider**
Hey all, 

here are the first macros with checked and partly increased statistics. If you think statistics are still not enough for some nuclides, let me know.

Cheers, 
Birgit

### CODE REVIEW

**Comment by vonsturm** [comment]
Looks good to me. The only thing I don't get is raw-cables-hv_at_holders-Po207-coin-000.mac I put this to compensate for the level which is killed in MaGe. But I put Po207 in an excited state.

> /gun/ion   82 207 0 1633.356 # Po207 with excitation energy

Furthermore the macros have to be copied to the other parts of the cables with the proper statistics.

Cheers,
Katharina

**Comment by BirgitSchneider** [comment]
I was confused where the Po207 should come from. But you mean the exicted state of Pb207, right? Then this makes sense :D I'm going to change it.
I'm still working on the other parts of the cables, which will follow next week.

Cheers, 
Birgit

**Comment by vonsturm** [comment]
> I was confused where the Po207 should come from. But you mean the exicted state of Pb207, right? 
O yes, my fault :D I meant Pb207 and the macro is for Pb207 (82,207) but I wrote Po207. I will also change it. So sorry...

Katharina

**Comment by vonsturm** [comment]
Why?

**Comment by BirgitSchneider** [comment]
I made a new request in order to prevent Po207 from still popping up somewhere.

**Comment by vonsturm** [comment]
OK :) also with a new commit there shouldn't be a problem...

**Pull request closed without merging**
