### PR TITLE
added electronics-cc3-K40-edep/coin

### PR DESCRIPTION
**Pull request by ThWester**
I added the cc3. From the screening results I would expect K40 contribution from the cc3 which is 10-20% of that from the 'main' components. Also it adds a component above the array, while coppershroud is dominantly below.

The cc3 doesnt fit in any of the other categories, so I added "electronics".
I changed the Makefile in Utils/post accordingly. Any other changes that need to be made because of that?

### CODE REVIEW

**Comment by gipert** [comment]
> Any other changes that need to be made because of that?

Nope, good you remembered to change the Makefile for post-production, I would have forgotten it!

P.S.: I see you didn't include `cc3.png`, did you produce it? I can do it for you if you want
P.P.S.: Seems that CC3 is made of Teflon in MaGe (2.165 g/cm3)

**Comment by ThWester** [comment]
> P.S.: I see you didn't include cc3.png, did you produce it? I can do it for you if you want

No I dont have it yet. I think you will be much quicker with that, because I dont really know how to do proper MaGe visualizations :P

**Comment by gipert** [comment]
Ok, merge at your convenience

**Comment by gipert** [comment]
I also started the simulations

**Pull request merged**
